"""PDF report formatter using fpdf2."""

from __future__ import annotations

from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

from fpdf import FPDF

from ipa_analyzer import __version__
from ipa_analyzer.core.context import AnalysisContext
from ipa_analyzer.detectors.base import Finding, Severity
from ipa_analyzer.reporters.base import BaseReporter
from ipa_analyzer.utils.scoring import calculate_risk_score

SEVERITY_COLORS = {
    "CRITICAL": (220, 53, 69),
    "HIGH": (253, 126, 20),
    "MEDIUM": (255, 193, 7),
    "LOW": (13, 110, 253),
    "INFO": (108, 117, 125),
}

GRADE_COLORS = {
    "A": (25, 135, 84),
    "B": (13, 110, 253),
    "C": (255, 193, 7),
    "D": (253, 126, 20),
    "F": (220, 53, 69),
}


class PDFReporter(BaseReporter):
    """Renders analysis findings as a styled PDF report.

    Unlike other reporters, this writes directly to a file and returns None.
    """

    def __init__(self, output_path: Path) -> None:
        self.output_path = output_path

    def report(
        self,
        context: AnalysisContext,
        findings: list[Finding],
    ) -> str | None:
        """Generate a PDF report and write it to self.output_path.

        Returns:
            None (writes to file).
        """
        risk = calculate_risk_score(findings)
        severity_counts = Counter(f.severity for f in findings)

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.add_page()

        # Title
        pdf.set_font("Helvetica", "B", 22)
        pdf.cell(0, 14, "iOS IPA Security Report", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        # App metadata
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(80, 80, 80)
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        pdf.cell(0, 7, f"App: {context.app_name}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 7, f"IPA: {context.ipa_path.name}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 7, f"Scanned: {timestamp}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(
            0,
            7,
            f"Analyzer: ipa-analyzer v{__version__}",
            new_x="LMARGIN",
            new_y="NEXT",
        )
        pdf.ln(4)

        # Risk score
        self._render_risk_score(pdf, risk.score, risk.grade)
        pdf.ln(6)

        # Severity summary
        self._render_severity_table(pdf, severity_counts, len(findings))
        pdf.ln(6)

        # Findings
        self._render_findings(pdf, findings)

        # Footer
        pdf.ln(10)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(
            0,
            5,
            f"Generated by ipa-analyzer v{__version__} on {timestamp}",
            new_x="LMARGIN",
            new_y="NEXT",
        )

        pdf.output(str(self.output_path))
        return None

    @staticmethod
    def _render_risk_score(pdf: FPDF, score: int, grade: str) -> None:
        r, g, b = GRADE_COLORS.get(grade, (80, 80, 80))

        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, f"Risk Score: {score}/100  |  Grade: {grade}")
        pdf.set_x(pdf.l_margin)
        pdf.ln(12)
        pdf.set_text_color(r, g, b)
        # Draw a simple score bar
        bar_width = pdf.epw
        filled = bar_width * min(score, 100) / 100
        pdf.set_fill_color(r, g, b)
        pdf.cell(filled, 4, "", fill=True)
        pdf.set_x(pdf.l_margin)
        pdf.ln(6)
        pdf.set_text_color(0, 0, 0)

    @staticmethod
    def _render_severity_table(pdf: FPDF, severity_counts: Counter, total: int) -> None:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 8, f"Summary ({total} findings)", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        # Render as a vertical list for reliability
        pdf.set_font("Helvetica", "B", 9)
        for sev in Severity:
            r, g, b = SEVERITY_COLORS.get(sev.name, (80, 80, 80))
            count = severity_counts.get(sev, 0)
            pdf.set_fill_color(r, g, b)
            pdf.set_text_color(255, 255, 255)
            pdf.cell(30, 7, f"  {sev.name}", border=0, fill=True)
            pdf.set_fill_color(240, 240, 240)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(20, 7, f"  {count}", border=0, fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    @staticmethod
    def _render_findings(pdf: FPDF, findings: list[Finding]) -> None:
        sorted_findings = sorted(findings, key=lambda f: (-f.severity.value, f.title))

        current_severity = None
        for finding in sorted_findings:
            # Ensure x is at left margin before each finding
            pdf.set_x(pdf.l_margin)

            if finding.severity != current_severity:
                current_severity = finding.severity
                pdf.ln(4)
                r, g, b = SEVERITY_COLORS.get(current_severity.name, (80, 80, 80))
                pdf.set_font("Helvetica", "B", 13)
                pdf.set_text_color(r, g, b)
                pdf.cell(
                    0,
                    9,
                    f"{current_severity.name} Findings",
                    new_x="LMARGIN",
                    new_y="NEXT",
                )
                pdf.set_draw_color(r, g, b)
                y = pdf.get_y()
                pdf.line(pdf.l_margin, y, pdf.l_margin + pdf.epw, y)
                pdf.ln(3)

            pdf.set_text_color(0, 0, 0)
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 7, finding.title, new_x="LMARGIN", new_y="NEXT")

            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(60, 60, 60)
            pdf.multi_cell(0, 5, finding.description, new_x="LMARGIN", new_y="NEXT")

            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(100, 100, 100)
            evidence_text = finding.evidence or ""
            if len(evidence_text) > 120:
                evidence_text = evidence_text[:117] + "..."
            pdf.multi_cell(0, 4, f"Evidence: {evidence_text}", new_x="LMARGIN", new_y="NEXT")
            owasp_cwe = f"OWASP: {finding.owasp}  |  CWE-{finding.cwe_id}"
            pdf.cell(0, 4, owasp_cwe, new_x="LMARGIN", new_y="NEXT")

            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(25, 135, 84)
            pdf.multi_cell(
                0,
                4,
                f"Remediation: {finding.remediation}",
                new_x="LMARGIN",
                new_y="NEXT",
            )
            pdf.set_text_color(0, 0, 0)
            pdf.ln(3)
